### PR TITLE
Add Darwin target

### PR DESCRIPTION
**Pull request by vicomte**
Make some adjustments for OSX, package naming and availability through Homebrew.

### CODE REVIEW

**Comment by witjoh** [comment]
Thx for the PR.  Could you also add rspec tests for darwin ?

**Comment by witjoh** [comment]
@vicomte Just forget the tests.  Seems I need to do some extra work.  And I'm starting updatinng this module to puppet 5+.
If you kan conform that your PR is working on Darwin, I'm willing to merge it.  Since I dont't have this platform, I'm not able to verify this.
Thx for the PR

**Comment by vicomte** [comment]
@witjoh Sorry for not responding earlier. I saw some VM based CI in there so was going to circle back around when I had more time. I am using my changes to push rvm and a ruby version to Mac minis on Sierra, High Sierra and Mojave at present. The only issues I have currently are that when OSX is upgraded sometime Brew loses the ability to set permissions on /usr/local correctly for dependency install but that is a whole different issue.

**Comment by witjoh** [comment]
@vicomte I can merge your PR.  For the issue you have when OSX is upgraded, we can make an issue for it.
I'm already rewriting the code for puppet5+ with your PR applied.  Before adding that, I can make a release first for those that still needs puppet 3 style.   I know it is EOL for some time, but many are still on this version.

**Comment by vicomte** [comment]
Sounds good. Last thing, I just realized I changed the method for gpg key verification in this change. I don't know if you have strong feelings about that. I know that on OSX when the other key was added it broke a lot of automation which precipitated our changes.

**Comment by witjoh** [comment]
Thinking to use https://forge.puppet.com/golja/gnupg
but seems mac ain't supported ... 
Used this already somewhere else with puppet5/6, still works :)
I leave it for now and will merge 
If something breaks, well, we have to fix it :)

**Pull request merged**
